= Aufgabe 02

== Übersetze den folgenden Text ins Deutsche

=== Songtext

.Entre dos Tierras
****
e puedes vender
Cualquier oferta es buena si quieres poder
Qué fácil es
Abrir tanto la boca para opinar
Y si te piensas echar atrás
Tienes muchas huellas que borrar

Déjame
que yo no tengo la culpa de verte caer
Si yo no tengo la culpa de verte caer
Pierdes la fe
Cualquier esperanza es vana y no sé qué creer
Pero olvídame,
que nadie te ha llamado, ya estás otra vez

Déjame
que yo no tengo la culpa de verte caer
Si yo no tengo la culpa de ver que
Entre dos tierras estás
Y no dejas aire que respirar
Entre dos tierras estás
Y no dejas aire que respirar
Déjalo ya
No seas membrillo y permite pasar
Y si no piensas echar atrás
Tienes mucho barro que tragar

Déjame
que yo no tengo la culpa de verte caer
Si yo no tengo la culpa de ver que
Entre dos tierras estás
Y no dejas aire que respirar
Entre dos tierras estás
Y no dejas aire que respirar

Déjame
que yo no tengo la culpa de verte caer
Si yo no tengo la culpa de ver que
Entre dos tierras estás
Y no dejas aire que respirar
Entre dos tierras estás
Y no dejas aire que respirar

---
_Songwriter:_ Enrique Bunbury / Joaquin Cardiel Gerico / Juan Valdivia Navarro / Pedro Andreu Lapiedra

Songtext von Entre dos Tierras © Warner/Chappell Music, Inc, Sony/ATV Music Publishing LLC

_Künstler:_ Héroes del Silencio

_Album:_ Senderos de traición

_Veröffentlicht:_ 1990

_Genre:_ Rock aus Spanien
****