= Aufgabe 02a

//Formatting block quotes
//http://www.seinan-gu.ac.jp/~shito/asciidoctor/html_chunk/chap43.html

== Übersetze den folgenden Text ins Deutsche

=== Songtext

[verse,"Entre dos Tierras","Héroes del Silencio"]
____
Te puedes vender
Cualquier oferta es buena si quieres poder
Qué fácil es
Abrir tanto la boca para opinar
Y si te piensas echar atrás
Tienes muchas huellas que borrar

Déjame
que yo no tengo la culpa de verte caer
Si yo no tengo la culpa de verte caer

Pierdes la fe
Cualquier esperanza es vana y no sé qué creer
Pero olvídame,
que nadie te ha llamado, ya estás otra vez

Déjame
que yo no tengo la culpa de verte caer
Si yo no tengo la culpa de ver que

Entre dos tierras estás
Y no dejas aire que respirar
Entre dos tierras estás
Y no dejas aire que respirar

Déjalo ya
No seas membrillo y permite pasar
Y si no piensas echar atrás
Tienes mucho barro que tragar

Déjame
que yo no tengo la culpa de verte caer
Si yo no tengo la culpa de ver que
Entre dos tierras estás
Y no dejas aire que respirar
Entre dos tierras estás
Y no dejas aire que respirar

Déjame
que yo no tengo la culpa de verte caer
Si yo no tengo la culpa de ver que

Entre dos tierras estás
Y no dejas aire que respirar
Entre dos tierras estás
Y no dejas aire que respirar
____

* _Songwriter:_ Enrique Bunbury / Joaquin Cardiel Gerico / Juan Valdivia Navarro / Pedro Andreu Lapiedra
* _Künstler:_ Héroes del Silencio
* _Album:_ Senderos de traición
* _Veröffentlicht:_ 1990
* _Genre:_ Rock aus Spanien
* _Musikvideo:_ https://youtu.be/6wMMcCkRAsk


=== Übersetzung

[verse,"Entre dos Tierras","Héroes del Silencio"]
____
Te puedes vender
Cualquier oferta es buena si quieres poder
Qué fácil es
Abrir tanto la boca para opinar
Y si te piensas echar atrás
Tienes muchas huellas que borrar

Déjame
que yo no tengo la culpa de verte caer
Si yo no tengo la culpa de verte caer

Pierdes la fe
Cualquier esperanza es vana y no sé qué creer
Pero olvídame,
que nadie te ha llamado, ya estás otra vez

Lass mich wissen,
dass ich nicht dafür verantwortlich bin, dass ich dich fallen sah
wenn ich nicht schuld bin, das zu sehen.
(Déjame
que yo no tengo la culpa de verte caer
Si yo no tengo la culpa de ver que)

Entre dos tierras estás
Y no dejas aire que respirar
Entre dos tierras estás
Y no dejas aire que respirar

Déjalo ya
No seas membrillo y permite pasar
Y si no piensas echar atrás
Tienes mucho barro que tragar

Déjame
que yo no tengo la culpa de verte caer
Si yo no tengo la culpa de ver que
Entre dos tierras estás
Y no dejas aire que respirar
Entre dos tierras estás
Y no dejas aire que respirar

Déjame
que yo no tengo la culpa de verte caer
Si yo no tengo la culpa de ver que

Entre dos tierras estás
Y no dejas aire que respirar
Entre dos tierras estás
Y no dejas aire que respirar
____
