= Aufgabe 01:

== Schreibe eine kurze Geschichte

=== La historia de potro Kai

Hay uno potro llama Kai.
El es en España
y
vive en Brato una ciudad pequeña.

Hoy el vamo para la playa.
El va
no para coche,
no para tren
pero
para pie.

Mas el no tiene crema solar.
El va a la famarcia.
No hay una farmacia aquí.
Kai no sabe donde.

El pregunta a una mujer.
"Pardon, ¿donde está una supermercado?"
"¿Hay un supermercado por aquí?"
La mujer dice:
"Está al lado de la éstation de Brato."
Sigue por la calle.
Gira a la izquierda,
pasa por la farmacia,
vaya a la izquierda el segundo a la derecha,
cerca de éstation esta el supermercado Hyperdino."
Kai dice
"Muchas gracias!
¡Adiós!"

El potro va a la supermercado.
En la supermercado el compra la crema solar y un sombrero.

La playa está aqui cerca.
El gira a la playa.
La playa y la mar es bonitos
mas la sol es muy caliente.

Kai tiene una insolación.
Por esto el va a la farmacia.
El sabo el camino.
"
Pasa la éstation
va a la izquerda el segundo
a la izquiera.
"

En la farmacia Kai pregunta
"¡Buenos días!
Tengo dolor de cabeza.
Tienes una aspirina, por favor?"
El hombre es Pedro.
El sabe Kai y
il dice
"Mi potrillo,
yo tengo unas aspirina.
Cuesta 13 euro."
Potro Kai dice
"Me gustaría dos, por favor.
Muchas gracias, Pedro."

Kai tiene sed.
Es uno restaurant aquí cerca.
El va a el restaurant Aguavista.
"Una mesa para uno, por favor.
Kai gusta agua.
"Disculpe.
Me gustaría ordenar, por favor.
Quisiera agua sin gaz y un pastel de chocolate, por favor."
Kai se gusta el pastel muy bien.
"La cuenta, por favor."
La comida estuvo deliciosa!"

Potro es cansado.
El quiere ir a casa.
No para pie,
pero en taxi.
No esta una taxi.
No esta un tren.
Pero un éstation para autobuso.
No mas un autobus.
Esta un biciclieta a vende y a rentra.
Kai rent el bicilieta.
Nuestro potrillo Kai va a la casa para biciclieta nuevo.
Kai hoy una días muy bien.
¡Buenas noches, Kai!










