= Aufgabe 01:

== Schreibe eine kurze Geschichte

=== La historia de potro Kai

Hay un potro, se llama Kai.
Él es de España
y
vive en Brato,
una ciudad pequeña.

Hoy el va para la playa.
Él no va en coche,
no va en tren,
pero
va a pie.

Mas/Pero él no tiene crema solar.
Él va al supermercado.
No hay un supermercado aquí.
Kai no sabe donde.

Él pregunta a una mujer.
"Perdon, ¿donde está un supermercado?"
"¿Hay un supermercado por aquí?"
La mujer dice:
"Está al lado de la estación de Brato."
Sigue por la calle.
Gira a la izquierda,
pasa por la farmacia,
vaya a la izquierda la segundo a la derecha,
cerca de estación está el supermercado Hyperdino."
Kai dice
"Muchas gracias!
¡Adiós!"

Él potro va al supermercado.
En el supermercado él compra la crema solar y un sombrero.

La playa está aquí cerca.
Él gira a la playa.
La playa y es mar son bonitos
mas el sol es muy caliente.

Kai tiene una insolación.
Por esto el va a la farmacia.
El sabo el camino.
"
Pasa la éstation
va a la izquerda el segundo
a la izquiera.
"

En la farmacia Kai pregunta
"¡Buenos días!
Tengo dolor de cabeza.
Tienes una aspirina, por favor?"
El hombre es Pedro.
El sabe Kai y
il dice
"Mi potrillo,
yo tengo unas aspirina.
Cuesta 13 euro."
Potro Kai dice
"Me gustaría dos, por favor.
Muchas gracias, Pedro."

Kai tiene sed.
Es uno restaurant aquí cerca.
El va a el restaurant Aguavista.
"Una mesa para uno, por favor.
Kai gusta agua.
"Disculpe.
Me gustaría ordenar, por favor.
Quisiera agua sin gaz y un pastel de chocolate, por favor."
Kai se gusta el pastel muy bien.
"La cuenta, por favor."
La comida estuvo deliciosa!"

Potro es cansado.
El quiere ir a casa.
No para pie,
pero en taxi.
No esta una taxi.
No esta un tren.
Pero un éstation para autobuso.
No mas un autobus.
Esta un biciclieta a vende y a rentra.
Kai rent el bicilieta.
Nuestro potrillo Kai va a la casa para biciclieta nuevo.
Kai hoy una días muy bien.
¡Buenas noches, Kai!










